// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-students.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.50.0";
import { z } from "npm:zod@^3.25.76";
var list_students_default = defineTool({
  name: "list_students",
  title: "List students",
  description: "List students from Ban Don Moon School. Optionally filter by academic year (Buddhist year, e.g. 2568), grade level, or classroom.",
  inputSchema: {
    academic_year: z.string().optional().describe("Thai Buddhist academic year, e.g. '2568'."),
    grade_level: z.string().optional().describe("Grade level, e.g. '\u0E1B.1', '\u0E1B.6'."),
    classroom: z.string().optional().describe("Classroom identifier, e.g. '1/1'."),
    limit: z.number().int().min(1).max(500).optional().describe("Max rows to return (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ academic_year, grade_level, classroom, limit }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!url || !key) {
      return { content: [{ type: "text", text: "Supabase env not configured" }], isError: true };
    }
    const supabase = createClient(url, key, { auth: { persistSession: false } });
    let q = supabase.from("students").select("*").limit(limit ?? 100);
    if (academic_year) q = q.eq("academic_year", academic_year);
    if (grade_level) q = q.eq("grade_level", grade_level);
    if (classroom) q = q.eq("classroom", classroom);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { count: data?.length ?? 0, students: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-teachers.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.50.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_teachers_default = defineTool2({
  name: "list_teachers",
  title: "List teachers",
  description: "List teachers from Ban Don Moon School. Optionally filter by academic year (Thai Buddhist year).",
  inputSchema: {
    academic_year: z2.string().optional().describe("Thai Buddhist academic year, e.g. '2568'."),
    limit: z2.number().int().min(1).max(500).optional().describe("Max rows to return (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ academic_year, limit }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!url || !key) {
      return { content: [{ type: "text", text: "Supabase env not configured" }], isError: true };
    }
    const supabase = createClient2(url, key, { auth: { persistSession: false } });
    let q = supabase.from("teachers").select("*").limit(limit ?? 100);
    if (academic_year) q = q.eq("academic_year", academic_year);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { count: data?.length ?? 0, teachers: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "ban-don-moon-school-mcp",
  title: "Ban Don Moon School MCP",
  version: "0.1.0",
  instructions: "Read-only access to Ban Don Moon School data. Use `list_students` to fetch students (filter by academic year / grade / classroom) and `list_teachers` for teacher records.",
  tools: [list_students_default, list_teachers_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
